<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Vyberieme, ktorá trieda sa spustí, keďže máme viacero metód Main() (jednu v Game a jednu v testoch) -->
    <StartupObject>Sokoban.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Sokoban.Tests\**" />
    <EmbeddedResource Remove="Sokoban.Tests\**" />
    <None Remove="Sokoban.Tests\**" />
  </ItemGroup>

</Project>
